### ISSUE TITLE
Song <> Share relation database schema changes

### ISSUE THREAD

**Issue by yss14** [yss14/musicshare#1010]
Seems like we got another schema change this year. During implementing crucial CRUD operations on songs over the last months, some problems occurred with the current song <> share relation database schema. To grasp those problem, we have to introduce the `share_songs` relation again. Introducing it again will change some behaviour of the current operations:

* [x] Add a song to a library
  * find all linked shares of this library
  * insert a song reference into `share_songs` for every linked share
* [x] Remove song from a library
  * check if song is referenced in playlists which are not part of the library (if so, show warning first)
  * for all libraries which referenced this song via a playlist the song is copied without file source to the library
  * for playlists belonging to a share, the song is removed from the playlist (normalize again!)
* [x] Update a songs info
  * still only possible for songs of own library
* [ ] Increment play count
  * accumulated play count is saved in `share_songs` table which make query easy and fast
  * in addition, the info is saved to `song_plays` table with user and share reference
* [x] Add user to a share
  * add reference of all library songs to share_songs
* [ ] Remove user from a share
  * same procedure as for removing a song, but applied to all shares and all songs belonging to the removed users library

In addition, we add a song hash to identify duplicates in merged views which can occur due to the remove song policies.
