### ISSUE TITLE
Apply share manifest of schema and policies

### ISSUE THREAD

**Issue by yss14** [yss14/musicshare#804]
After a long evaluation how to design the idea of owning a library but at the same time sharing songs with near friends, the following manifest with rules and policies was established:

Each user owns a `Library` with songs, playlists, albums, etc...
To share all those artefacts with friends, `Shares` can be created, which just link libraries and thus have a pool of songs from all linked libraries. A `Share` itself cannot own songs or albums, only playlists. 
In version one edit artefacts of linked libraries is permitted. Later, suggested corrections are possible which have to be approved by the owner of an artefact.

Todos:
* [x] Backend
  * [x] Song query of a `Share` should return all songs from all linked `Libraries`
  * [x] Edit of songs from other linked libraries is permitted
  * [x] Edit of playlists from other linked libraries is permitted
* [x] Frontend
  * [x] Renamed library tab to `All`
  * [x] Introduce an all view which combines all songs and all playlists
  * [x] Couple playlist view to selected share
  * [x] Split shares nav dropdown into two sections `Library` and `Shares`
  * [x] Add playlist should create a playlist under the currently selected share
  * [x] Shares acting as a proxy to access linked Songs
  * [x] Edit of songs from other linked libraries is permitted
  * [x] Edit/Add of playlists from other linked libraries is permitted
  * [x] Songs are always uploaded to the user's library
  * [x] `songTypes`, `genres`, `artists`, `playlists`, `tags` of Share return aggregated data (#821)
