### ISSUE TITLE
Share management

### ISSUE THREAD

**Issue by yss14** [yss14/musicshare#850]
A share should have an owner, who has rights to invite/kick members, rename a share, and change member permissions.
For now, there will be no registration in the normal sense. A user has to be invited by another user to get access. By this process, also a respective `Library` is created for an invited user.

* Backend
  * [x] Rename share mutation
  * [x] Delete share mutation
  * [x] Invite user mutation
  * [x] Revoke user invitation
  * [x] Create share mutation set user owner
  * [x] Update share user permission check if user of request is owner, otherwise deny
  * [x] Distinguish between pending and accepted share users
  * [x] Leave share mutation
* Frontend
  * [x] Shares dropdown add `Add share` button
  * [x] Add settings icon next to shares which opens share settings modal
  * [x] Share settings modal either user view (leave share) or owner view (name, members, delete share, leave share)
